name: CI

on:
  [push]
jobs:

  build_tests:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
 
    - name: Building tests
      shell: bash
      run: |
          git submodule update --init --recursive
          cmake -B build
          cd build
          make
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: test
        shell: bash
        run: |
          git submodule update --init --recursive
          cmake -B build
          cd build
          make ./tests
          ./tests

