name: CI

on:
  [push]
jobs:

  build_tests:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
 
    - name: Building tests
      shell: bash
      run: |
          git submodule update --init --recursive
          cmake -B build
          cd build
          make
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: test
        shell: bash
        run: |
          git submodule update --init --recursive
          cmake -B build
          cd build
          make ./tests
          ./tests
      - name: lcov
        run: |
         sudo pip install --user cpp-coveralls
         sudo apt-get install -y lcov
      - name: run
        run: |
         lcov --capture --directory output/CMakeFiles/banking.dir/banking --output-file ./lcov.info
         lcov --remove ./lcov.info '/home/runner/work/tp-lab05/tp-lab05/third-party/gtest/*' -o ./lcov_filtered.info
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: "./lcov_filtered.info"
          github-token: ${{ secrets.github_token }}

